######################################################################
# Automatically generated by qmake (3.0) ??? ?? 6 17:29:56 2014
######################################################################

TEMPLATE = app
TARGET = capslock
INCLUDEPATH += .
QT+=widgets
# Input
SOURCES += main.cpp \
    mainwindow.cpp

HEADERS += \
    mainwindow.h

RESOURCES=capslock.qrc

LIBS+=-lX11
